#include<stdio.h>
#include "cli.h"
#include"benchmark.h"
#include"helpers.h"
#include"genmath.h"

int main(int argc , char** argv){
    struct arg_str *gen = arg_strn(
        "g",
        "generate",
        "<m * n>",
        1 ,5 ,
        "generate upto 5 matrices of any size (eg 2x2 , 5x3 ..etc) ");

    struct arg_int *select =  arg_intn(
        "s",
        "select",
        "<idx>",
        1, 5 ,
        "select from the list of matrices generated by generate flag "); 

    struct arg_str *ops = arg_str1(
        "o",
        "operate",
        "<op>",
        "choose the operation ( mul , transpose , invert , det etc) " );

    struct arg_lit *help = arg_lit0(
        "h",
        "help",
        "Lists out all flags available ");

    struct arg_int *rep = arg_intn(
        "r",
        "repeat",
        "<rep>",
        0, 10000 ,
        "repeats the operation (0-10000) ");

    struct arg_end *end = arg_end(20);
    void *argtable[] = {gen,select,ops,help,rep,end,NULL};
    int nerrors = arg_parse(argc, argv, argtable);
    /* if parsing fails */
    if (nerrors > 0){
        arg_print_errors(stdout,end,argv[0]);
        printf("Try --help for more info \n");
        arg_freetable(argtable,sizeof(argtable)/sizeof(argtable[0]));
        return 1;
    }
    /* if help flag is invoked */
    if (help->count > 0){
        printf("Uses :\n");
        arg_print_syntax(stdout,argtable , "\n");
        printf("\nOptions:\n");
        arg_print_glossary(stdout,argtable,"  %-25s %s\n");
        arg_freetable(argtable,sizeof(argtable)/sizeof(argtable[0]));
    }
    /* handle rest of flags */

    /* generate matrices */
    if (gen->count > 0){
        Matrix matrices [gen->count]; 
       for (int i = 0 ; i < gen->count ; ++i){
            int rows , cols;
            rows = gen->sval[i][0];
            cols = gen->sval[i][2];
            matrices[i] = voidmatrix(rows,cols);
       }
    }
}
